# Generated by Django 4.2 on 2023-05-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
