# Generated by Django 4.2 on 2023-04-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField()),
                ('barrio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.barrio')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.establecimiento')),
                ('id_Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cliente')),
            ],
        ),
    ]
