# Generated by Django 4.2 on 2023-04-26 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_barrio_establecimiento_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='direccion',
            field=models.CharField(default=datetime.datetime(2023, 4, 26, 1, 19, 3, 187970, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
