# Generated by Django 4.2 on 2023-04-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.IntegerField(max_length=255)),
                ('id_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cuenta')),
            ],
        ),
    ]
