# Generated by Django 4.2 on 2023-05-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_recaudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recaudos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
