# Generated by Django 4.2 on 2023-05-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_barrio_estado_cliente_estado_cuenta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='barrio',
            field=models.ForeignKey(limit_choices_to={'estado': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.barrio'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='establecimiento',
            field=models.ForeignKey(limit_choices_to={'estado': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.establecimiento'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_Cliente',
            field=models.ForeignKey(limit_choices_to={'estado': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cliente'),
        ),
        migrations.AlterField(
            model_name='recaudos',
            name='id_cuenta',
            field=models.ForeignKey(limit_choices_to={'estado': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cuenta'),
        ),
    ]
